Feat: Firmware Check
Max-Mobility/permobil-client pull request #837
Opened 2020-09-03 19:01 UTC by bradmartin

- Flattening some of the current firmware check/download processes in the `updates` for re-use.
- Adding firmware check/download when device connects to SD (will determine final handling with Ben/William how we handle the UX).
- Adding firmware check/download when certain settings are changed.

2020-09-08 15:28 UTC, finger563 requested changes
we probably want to roll-back / remove from this PR the changes to all the `*.js` files that were committed.

Also - see my comment about moving the `currentVersions` structure management and storage directly into the new utils file instead of having to have the logic / state within both the `updates-view-model` and the `main-view-model`

2020-09-08 15:28 UTC, finger563 commented on apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
> +
It seems like we could refactor this code (which is shared by the `updates-view-model` IIRC) to be within the utilities - perhaps just requiring us to pass the service or itself directly accessing the service. That way there's only one place which contains the firmware metadata and file information and the `main-view-model` and `updates-view-model` can both call functions which internally access that data.

2020-09-08 15:28 UTC, finger563 commented on package.json
> +    "ci.build.base.setup": "echo no | npm i -g nativescript@6.5.1 && tns usage-reporting disable && tns error-reporting disable && npm i && npm run global.installs",
Why the pin to `6.5.1`?

2020-09-08 16:16 UTC, bradmartin commented on package.json
> +    "ci.build.base.setup": "echo no | npm i -g nativescript@6.5.1 && tns usage-reporting disable && tns error-reporting disable && npm i && npm run global.installs",
7.0 was published and we're not updated for it yet, so the builds fail with latest CLI. Once we get the apps updated, currently working on that on a branch, will try to push it up today and keep iterating (done in another day or two) then we can unpin it.

2020-09-08 16:20 UTC, bradmartin commented on apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
> +
There was some reason I didn't refactor it entirely into the utils, I believe it was because one of the services was failing to register with the DI mech so it was crashing. Looks like I left the `kinveyService` in this because it failed to pull into the utils, the SQLiteService does seem to work properly. Not sure if it was timing related or what though, but I'll try again and see if more can't be isolated to keep it stable across the usages.

2020-09-08 16:21 UTC, bradmartin commented on apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
> +
And yea, I keep forgetting to not commit all the files so those JS files keep ending up on my pushes. I'm going to add those specific files to the gitignore with this PR.

2020-09-08 16:39 UTC, bradmartin reviewed
Now I'm confused why we were NOT ignoring some files in the ns-core dirs... :/

2020-09-11 14:41 UTC, finger563 commented on apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
> +
Looking through this some more - at the very least we don't need to download the actual firmware files here, so lines 2950 - 2983 shouldn't be needed; we'll likely want to

* look at the versions on the server (the `mds` returned by `_kinveyService.downloadFirmwareFiles()`)
* compare the versions on the server to the versions on the smartdrive
* pop up an action dialog which informs the user that a firmware update is available and gives them a button to go to the wireless updates page (which will then do the check / download accordingly), or allows them to postpone / ignore the update for now

2020-09-11 14:43 UTC, finger563 commented on apps/wear/smartdrive/app/utils/smartdrive-utils.ts
> +    const current = this.currentVersions[fwName];
where is `this.currentVersions` coming from here?

2020-09-24 14:16 UTC, finger563 commented on apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
> +      .downloadFirmwareFiles()
this should probably be renamed (git blame emfinger) since it's actually only downloading the firmware file metadata

2020-10-15 17:28 UTC, finger563 submitted a review, later dismissed

2020-10-15 17:28 UTC, finger563 commented on apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
> +
```suggestion
```

removed unneeded comment addition

2020-10-15 17:28 UTC, finger563 commented on apps/wear/smartdrive/app/pages/main-page/main-view-model.ts
> +      this._checkForUpdates();
```suggestion
      // According to Ben: only check for firmware updates on app startup:
      this._checkForUpdates();
```

2020-10-15 17:32 UTC, finger563 approved these changes

2020-10-15 17:43 UTC, merged